INSERT INTO Breeds (Name) VALUES ('Domestic Long Hair'),
('DSH/Unknown'),
('Hound/Mix'),
('Domestic Short Hair'),
('Labrador Retriever'),
('Pit Bull Terrier/Bully Breed Mix'),
('Pitbull'),
('Cattle Dog/Mix'),
('Domestic Medium Hair'),
('Domestic Long Hair'),
('Pitbull'),
('Labrador Retriever/Mix'),
('Domestic Short Hair'),
('Domestic Short Hair'),
('Pitbull'),
('Labrador Retriever'),
('Domestic Short Hair'),
('Akita/Husky'),
('Domestic Short Hair'),
('Maltese'),
('Domestic Short Hair'),
('Pitbull'),
('Schnauzer'),
('Beagle'),
('Domestic Short Hair'),
('Domestic Short Hair'),
('Jack Russell Terrier/Mix'),
('Mastiff/Mix'),
('Pitbull'),
('Pitbull'),
('Pitbull'),
('Pitbull/Jack Russell Terrier'),
('Pit Bull Terrier/Boxer'),
('Hound'),
('Labrador Retriever/Mix'),
('Pitbull/Corgi'),
('Pitbull/Whippet'),
('Border Collie/Mix'),
('Rat Terrier'),
('Pitbull'),
('Pitbull/Mix'),
('Pug'),
('Pitbull/Labrador Retriever'),
('Domestic Long Hair'),
('German Shepherd Dog'),
('Domestic Short Hair'),
('Labrador Retriever/Mix'),
('Pitbull'),
('Domestic Short Hair'),
('Bully Breed Mix'),
('Domestic Short Hair'),
('Domestic Short Hair'),
('Beagle'),
('Domestic Short Hair'),
('Boxer'),
('Domestic Short Hair'),
('Domestic Short Hair'),
('Bully Breed Mix'),
('Domestic Short Hair'),
('Australian Shepherd'),
('Beagle/Mix'),
('Domestic Short Hair'),
('Domestic Short Hair'),
('Domestic Short Hair'),
('Domestic Short Hair'),
('Australian Shepherd/Border Collie'),
('Domestic Short Hair'),
('Bully Breed Mix/Boxer'),
('Boxer/American Staffordshire Terrier'),
('Domestic Medium Hair'),
('Domestic Short Hair'),
('Domestic Long Hair'),
('Domestic Short Hair'),
('Domestic Short Hair'),
('Golden Retriever/Border Collie'),
('Bully Breed Mix'),
('Domestic Short Hair'),
('Domestic Short Hair'),
('Domestic Short Hair'),
('Jack Russell Terrier/Beagle'),
('Husky');